### ISSUE TITLE
minor edit to biome labels

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#102]
For mixed broadleaf evergreen/ conifer forests, the calculator displays "mixed broadleaf conifer forest", which erroneously implies the existence of broadleaf conifer species. Please change to  "mixed forest"

**Comment by potterzot** [comment]
Fixed [here](https://github.com/ebimodeling/ghgvcR/blob/bc6e3d6d2658168f62c76cf242e6475bcbc386a5/R/plots.R#L24-L30)
