### ISSUE TITLE
Find appropriate citation for "Maximizing ecosystem services while meeting U.S. bioenergy goals."

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvc#103]
From @dlebauer originally: What is the appropriate citation for 

    Maximizing ecosystem services while meeting U.S. bioenergy goals. BioScience

@teixeirak said she was not aware of any publication by that name.

Best I was able to find was a paper in revision listed in Sarah C Davis' [pdf CV](http://www-app.igb.illinois.edu/davissc/DavisCV2011new.pdf):

    DeLucia E.H., K.J. Anderson-Teixeira, B.D. Duval, S.C. Davis, W.J. Parton, S.P. Long. 
    Maximizing ecosystem services while meeting US bioenergy goals. in revision.

**Comment by teixeirak** [comment]
Davis SC, Parton WJ, Del Grosso SJ, Keough C, Marx E, Adler PR, and DeLucia EH<http://www.life.illinois.edu/delucia/Davis%20-%20DeLucia%20Frontiers.pdf> (2011) Impact of second-generationa biofuel agriculture on greenhouse-gas emissions in the corn-growing regions of the US. Frontiers in Ecology and the Environment (doi:10.1890/110003)

On Mar 13, 2017, at 10:51 PM, Nicholas Potter <notifications@github.com<mailto:notifications@github.com>> wrote:


From @dlebauer<https://github.com/dlebauer> originally: What is the appropriate citation for

Maximizing ecosystem services while meeting U.S. bioenergy goals. BioScience


@teixeirak<https://github.com/teixeirak> said she was not aware of any publication by that name.

Best I was able to find was a paper in revision listed in Sarah C Davis' pdf CV<http://www-app.igb.illinois.edu/davissc/DavisCV2011new.pdf>:

DeLucia E.H., K.J. Anderson-Teixeira, B.D. Duval, S.C. Davis, W.J. Parton, S.P. Long.


Maximizing ecosystem services while meeting US bioenergy goals. in revision.

**Comment by teixeirak** [comment]
I'm not sure where this is needed. It is correctly cited in the in-prep paper, so I will close this issue.
