### ISSUE TITLE
In biome parameter selection, round display of numerical data to appropriate digits.

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvc#107]
Edit biome_defaults.csv to add a column with  number of digits for each variable.

**Comment by potterzot** [comment]
Make 3 the default.

**Comment by teixeirak** [comment]
I added a column to biome_defaults.csv ("decimal_points") indicating the maximum number of digits after the decimal point that should be displayed for each variable. Note that this is the maximum--as opposed to the standard-- for each variable; we do not want to add zeroes when the original source has fewer decimal points.

**Comment by potterzot** [comment]
Thanks @teixeirak. I'm moving this issue to ghgvcR since that is where the rounding will happen and also where the values are read in and reported.
