### ISSUE TITLE
Determine where we will put inputs and outputs

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#11]
some working directory can be assumed, then add `run` and `out` subdirectories.

these can be set in the [`config.xml`](https://github.com/ebimodeling/ghgvcR/blob/master/inst/config.xml) as 1st level tags `rundir` and `outdir`, consistent with the use in [PEcAn settings file (see wiki:)](https://github.com/PecanProject/pecan/wiki/PEcAn-Configuration#run-setup)
 
When we want to save old runs, we can look more closely at the PEcAn approach (where a subdirectory corresponding to the `runs.id` field in BETYdb is auto-generated).

Currently, ruby writes out to `$HOME/ghgvcR/inst` and reads from `$HOME/ghgvcR/inst/extdata`. This is an artifact. These should all be replaced by `run` and `out` in the ruby code, and then when the ghgvcR script is run, the locations of these directories can be passed as arguments to the `ghgvc_script`, i.e.:

```sh
ghgvc_script.R $RUN $OUTPUT
```

This task requires modification of both the ruby and R code (see [ghgvcR issue 1](https://github.com/ebimodeling/ghgvcR/issues/1)).

**Comment by potterzot** [comment]
I think this is done as well, pending review of whether you want the `run` and `out` folders in ghgvc/tmp/. For example, on my installation, the full path to the output folder is `/opt/ghgvc/ghgvc/tmp/out/` and it contains `ghgv.json` and `ghgv.csv`. In contrast `run/` contains `biome.json` and `multisite_config.xml`.

It's probably worth noting that these are not removed on exit, so when developing, we should be careful to remove them before rerunning the server or they can be misleading.
