### ISSUE TITLE
Attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by caseyhofford** [ebimodeling/ghgvc#118]
Unlike #117 This error occurs on 'get_biome', before attempting to do any calculation. 

Causes a different error in ghgvcr

```
ghgvcr_1     | Error in .subset2(x, i, exact = exact) :

ghgvcr_1     |   attempt to select less than one element in get1index

ghgvcr_1     | Calls: <Anonymous> -> as.list -> [[ -> [[.data.frame -> <Anonymous>
```

This is probably happening here [biome.R#L328](https://github.com/ebimodeling/ghgvcR/blob/d53f01dedd280e367ca4ae775c342f793548bfee/R/biome.R#L328)

since this is the only location where as.list is used in ghgvcr

The full output from this error is below.

```
app_1        | Started GET "/get_biome?lng=-65&lat=-42" for 172.22.0.4 at 2018-11-02 23:13:21 +0000

app_1        | Cannot render console from 172.22.0.4! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

app_1        | Processing by WorkflowsController#get_biome as HTML

app_1        |   Parameters: {"lng"=>"-65", "lat"=>"-42"}

ghgvcr_1     | Error in .subset2(x, i, exact = exact) :

ghgvcr_1     |   attempt to select less than one element in get1index

ghgvcr_1     | Calls: <Anonymous> -> as.list -> [[ -> [[.data.frame -> <Anonymous>

app_1        | Completed 500 Internal Server Error in 3569ms

app_1        |

app_1        |

app_1        |

app_1        | Rserve::Connection::EvalError (eval failed: Packet[cmd=2130771970,len=<nil>, con='<nil>', 
status=error:'Unknown variable/method'(127)]):

app_1        |

app_1        | app/services/biome.rb:11:in `list'

app_1        | app/controllers/workflows_controller.rb:40:in `get_biome'

webserver_1  | 75.70.93.123 - - [02/Nov/2018:23:13:25 +0000] "GET /get_biome?lng=-65&lat=-42 
HTTP/1.1" 500 77880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"

webserver_1  | 75.70.93.123 - - [02/Nov/2018:23:13:26 +0000] "GET /favicon.ico HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
```

The traceback for this error in R

```
5: (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, 
       i, exact = exact))(x, ..., exact = exact)
4: `[[.data.frame`(biome_defaults, biome_code) at #314
3: biome_defaults[[biome_code]] at #314
2: as.list(as.character(biome_defaults[[biome_code]])) at #314
1: get_biome(-65, -42)
```

happens at the following locations as well:
```
Parameters: {"lng"=>"-108", "lat"=>"67"}
```

**Comment by dlebauer** [comment]
biome_code <- subset(fao_biomes, CODE == tolower(res$fao))[[biome_code]]

Says find the subset of records in the fao_biomes data frame where the value of CODE is equal to res$fao converted to lower case, and then just take the values in the biome_code column

_____________________
David LeBauer, PhD
Director of Data Science for the Arizona Experiment Station
1230 N Cherry Avenue, Tucson, Arizona 85721
207 BSRL
University of Arizona
520-621-4381
dlebauer@email.arizona.edu

________________________________

**Comment by teixeirak** [comment]
@caseyhofford, is this still a problem?

**Comment by caseyhofford** [comment]
@teixeirak this is still a problem.

This issue seems to happen if res$fao is "NA." for the selected coordinates and the biome code is "APX" or "GX".  I think this only happens when a point in the ocean is selected. I have added a check that just prints a message to the stdout.

This allows the requests to succeed, but it then allows biome types to be selected that don't make any sense for the ocean. It provides the following biome options:
```
 Native:
Broadleaf Evergreen Forest
Broadleaf Deciduous Forest
Shrub
Grass
Agroecosystem:
Grassland Pasture
Cropland
```

It also produces a chart with data only for greenhouse gas value:
![image](https://user-images.githubusercontent.com/8454154/77960937-eff53080-728d-11ea-87f3-c408e98401f4.png)

@teixeirak @dlebauer Would it be better to throw an error so that selecting points in the ocean does not give a result? Ideally we would catch this error in the rails app and give the user a meaningful notification rather than having it fail 'silently.'

**Comment by caseyhofford** [comment]
For now, I ghgvcR get_biome will return a JSON object containing an error message rather than thte biomes. The error could be used to notify a user. This prevents an error from occuring, and prevents any ecosystems from being displayed in the selector. :
![image](https://user-images.githubusercontent.com/8454154/77963136-b3c3cf00-7291-11ea-973c-e5506b96d646.png)

**Comment by caseyhofford** [comment]
closed in commit 927c462b617d391d7afb7b81445690c24e23e5fa

**Comment by caseyhofford** [comment]
It looks like FAO_Biomes has a 'water' code that would set the biome code to '0'. Is this what we want instead?

**Comment by teixeirak** [comment]
Thanks for working on this. I think either is fine so long as no terrestrial biomes show up when the pin is dropped in the water.
