### ISSUE TITLE
fix plot display

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#119]
There are three related issues that I believe were introduced upon addition of the option to display technical and non-technical output.

- [x] Please make the primary / default display the technical one.
- [x] The numbers on the graph output by R are the technical units (CO2 emission equivalents). It appears that an attempt was made to use the same plot with different axis labels, but this doesn't work. We would need to make two separate plots in R with different numbers and title on the x axis. If we go this route, I will provide instructions in the ghvcR repo.
- [x] If the axis label will be assigned outside R, fix the jumbled axis label on the technical plot:
<img width="1022" alt="screen shot 2018-11-03 at 8 35 12 am" src="https://user-images.githubusercontent.com/6355854/47952300-68de4480-df43-11e8-8dc1-26726a8dc0f0.png">
We want it to look like this:
<img width="995" alt="screen shot 2018-11-03 at 8 38 30 am" src="https://user-images.githubusercontent.com/6355854/47952326-e1dd9c00-df43-11e8-859e-5da9987953d0.png">

The separate plots are a cool feature, but not essential at this point. If this can be easily fixed (i.e., if its easy to pass two separate plots from R), its worth doing so. However, I wouldn't want to hold up progress for this if its tricky. 
@caseyhofford, please let me know how you would like to proceed.

**Comment by caseyhofford** [comment]
Encountering issues using svg injection libraries as they expect a file as an input, not a string.

**Comment by teixeirak** [comment]
PNG files are fine with me.

**Comment by caseyhofford** [comment]
https://github.com/ebimodeling/ghgvcR/blob/d53f01dedd280e367ca4ae775c342f793548bfee/R/plots.R#L44

I added an if statement here in GHGVCR because it looks to me like that for loop is supposed to only execute when the units are miles driven. It simply multiplies all crv values by 1.86. Is this the only adjustment that needs to be made to export the other chart? It seems to only change the second two graphs, leaving biogeochemical the same.

![image](https://user-images.githubusercontent.com/8454154/54303431-9473da00-4588-11e9-8880-a72a2776c7e1.png)

![image](https://user-images.githubusercontent.com/8454154/54303454-9fc70580-4588-11e9-9614-2b8ceae8c9a8.png)

I haven't read the bulk of this function though, and I may be missing something.

**Comment by teixeirak** [comment]
This sounds partially right. All that needs to be done is a simple multiplication, along with changing the text on the axis. 
However, I don't understand why the biogeochemical portion doesn't change.

**Comment by teixeirak** [comment]
I'm a bit confused. Please clarify what those two plots are? Before and after your changes? Or technical (Mg CO2) vs public (miles driven) version?

**Comment by caseyhofford** [comment]
Sorry, that is technical vs. miles driven for the same point. Some plots seem to display exactly the same, some just the net value changes.

The changes should be consistent for all of the values, right?

**Comment by teixeirak** [comment]
Yes, all values in the technical plot should be multiplied by the same factor (1.86, although I want to double check).

**Comment by caseyhofford** [comment]
OK, I am a little intimidated by the [plot_ghgv function](https://github.com/ebimodeling/ghgvcR/blob/d53f01dedd280e367ca4ae775c342f793548bfee/R/plots.R#L14).  It looks like these three variables "CRV_BGC", "CRV_BIOPHYS", "CRV_NET" are multiplied by that factor on [line 44 ](https://github.com/ebimodeling/ghgvcR/blob/d53f01dedd280e367ca4ae775c342f793548bfee/R/plots.R#L44) however the resulting charts have points changing inconsistently. Are those three variables the only variables that should have to be multiplied?

**Comment by caseyhofford** [comment]
OK, I think I fixed this, for some reason only some of the required fields were being multiplied in that loop. Try out a few at http://ghgvc.caseyhofford.com/ and let me know if the results look right.

**Comment by caseyhofford** [comment]
And here's an example where it looks like everything adjusted correctly.
![image](https://user-images.githubusercontent.com/8454154/54321900-90f84700-45b8-11e9-81d6-54c4ab7d30a8.png)
![image](https://user-images.githubusercontent.com/8454154/54321910-99e91880-45b8-11e9-8571-52d78fca6c8d.png)

**Comment by teixeirak** [comment]
This looks right from all I've seen.  Before closing this issue, there are several more, hopefully very easy, fixes:

- [ ] 1. The black dots on the graphs (representing net effects ) appear to be off in both the Biophysical and Climate Regulating Value panels. They are correct in the Biogeochemical panel. Here's what they should be:
Biogeochemical: net = ongoing exchange +  storage
Biophysical: net = latent heat flux + net radiation
Climate regulating value: net = biogeochemical + biophysical
Dots should be shown only when both terms are present

- [ ] 2. Change graphs to show Climate Regulating Value only when both biogeochemical and biophysical data are present

- [ ] 3. Rename panels in graph:
"Biogeochemical"--> Greenhouse Gas Value
"Biophysical"--> Local Biophysical Forcings
"Climate Regulating Value" stays the same

- [ ] 4.  Please replace the labels on the tabs:
"technical"--> Emission equivalents
"miles driven"--> Driving equivalents

**Comment by teixeirak** [comment]
This looks great, thanks! 
A couple little things I noticed on one output plot:

- [ ] there should be no dot on “local biophysical forcings” unless there’s data.
- [ ] also, I don't see a black dot for greenhouse gas value for cropland (I wonder if this is related to the above-- a little mixup when fixing `1` above?)

<img width="1028" alt="Screen Shot 2019-09-21 at 6 06 38 AM" src="https://user-images.githubusercontent.com/6355854/65372287-e1252580-dc3b-11e9-9be4-7c7174bebb7e.png">

**Comment by teixeirak** [comment]
The graphs are all correct as far as I can tell. Many thanks, @caseyhofford!
