### ISSUE TITLE
Add "adjust settings" button

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#12]
Allow user to adjust settings for previously added locations

![image](https://f.cloud.github.com/assets/464871/1845508/61cbe41e-758e-11e3-85ed-e12166a15ae4.png)

**Comment by teixeirak** [comment]
I'd like to highlight this issue as one of the important changes that should be made prior to publication. 

The adjust settings button should bring up a box with the following options, which will adjust the parameters that go into all calculations for a given run:
1-set time parameters: T_E (ecosystem time frame), T_A (analytical time frame), r (annual discount rate)
2- select whether or not to include biophysical components. In addition to influencing the calculations, this selection should determine whether final graphical output includes panels for "biophysical" and "climate regulating value"
3- select greenhouse gases to be included (CO2, CH4, N2O)
4- if biophysical is selected, select which elements to include (Rnet and/or LE)

Please let me know if any clarification is needed.

**Comment by teixeirak** [comment]
An addition to the above, please include option to include  anthropogenic management emissions, F_{anth}. (See also https://github.com/ebimodeling/ghgvcR/issues/8)

**Comment by dlebauer** [comment]
The function `place_google_maps_pin` is here: https://github.com/ebimodeling/ghgvc/blob/47b65e5bee012a77132756208eca13f2336ec5a7/app/assets/javascripts/workflows.js#L23

I suspect where it is used on https://github.com/ebimodeling/ghgvc/blob/47b65e5bee012a77132756208eca13f2336ec5a7/app/assets/javascripts/workflows.js#L160 is where the option of entering by lat/ lon, can be added
