### ISSUE TITLE
failed .csv file download

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#120]
When I try to download the .csv file (passed from R for user download), I get this:
<img width="844" alt="screen shot 2018-11-03 at 8 48 21 am" src="https://user-images.githubusercontent.com/6355854/47952425-58c76480-df45-11e8-871d-f0b5bdf17ec5.png">

**Comment by teixeirak** [comment]
This file should be passed back to Rails from R in a json file.

**Comment by potterzot** [comment]
Just a comment here that may help: R passes a json string (not a file) back to the Rails server, and there is not a `download_csv` method in the [workflows_controller.rb](https://github.com/ebimodeling/ghgvc/blob/78143cbe7b24181fcab1b3c36633d6d74ec035e7/app/controllers/workflows_controller.rb#L1). I thought that there was this method in the past, and I wonder if @jaydorsey removed it in this commit?

Anyway, a fix should be to add a download_csv method in the `workflows_controller.rb` that takes the json string that is returned from R and converts to csv before triggering a download.

**Comment by caseyhofford** [comment]
There is a JS function called ConvertToCSV that creates a csv where every value is a row. The download csv button will just use this function to export a csv from the returned json object. A JS function could be written where rows are each selected biome, which might be better.

**Comment by teixeirak** [comment]
What would be the difference in terms of output?

**Comment by caseyhofford** [comment]
The current output looks like this 

```
site_1_data,Broadleaf_Evergreen_Forest,name,Broadleaf_Evergreen_Forest
site_1_data,Broadleaf_Evergreen_Forest,lat,-4
site_1_data,Broadleaf_Evergreen_Forest,lng,-54.94
site_1_data,Broadleaf_Evergreen_Forest,S_CO2 [Mg CO2-eq ha-1 100 yrs-1],1106.8095
site_1_data,Broadleaf_Evergreen_Forest,S_CH4 [Mg CO2-eq ha-1 100 yrs-1],39.6976
site_1_data,Broadleaf_Evergreen_Forest,S_N2O [Mg CO2-eq ha-1 100 yrs-1],24.0898
site_1_data,Broadleaf_Evergreen_Forest,F_CO2 [Mg CO2-eq ha-1 100 yrs-1],43.1091
site_1_data,Broadleaf_Evergreen_Forest,F_CH4 [Mg CO2-eq ha-1 100 yrs-1],7.6674
site_1_data,Broadleaf_Evergreen_Forest,F_N2O [Mg CO2-eq ha-1 100 yrs-1],-74.3763
site_1_data,Broadleaf_Evergreen_Forest,D_CO2 [Mg CO2-eq ha-1 100 yrs-1],1149.9186
site_1_data,Broadleaf_Evergreen_Forest,D_CH4 [Mg CO2-eq ha-1 100 yrs-1],47.365
site_1_data,Broadleaf_Evergreen_Forest,D_N2O [Mg CO2-eq ha-1 100 yrs-1],-50.2865
site_1_data,Broadleaf_Evergreen_Forest,swRFV [Mg CO2-eq ha-1 100 yrs-1],508.3967
site_1_data,Broadleaf_Evergreen_Forest,latent [Mg CO2-eq ha-1 100 yrs-1],632.4078
site_1_data,Broadleaf_Evergreen_Forest,crv [Mg CO2-eq ha-1 100 yrs-1],1271.0082
```

rather than having a row for Broadleaf_Evergreen_Forest with S_N2O, D_N2O, etc. as columns.

**Comment by teixeirak** [comment]
It would be preferable to have those listed in columns.

**Comment by caseyhofford** [comment]
OK, that will be fairly easy to do.
