### ISSUE TITLE
update conversion factor for miles driven

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#124]
The conversion factor from Mg CO2-eq to miles driven is approximately correct, but I need to update it with recent values for average car fuel economy and CO2 production per gallon gas, with citations.

**Comment by teixeirak** [comment]
I recently retrieved these values:
8887 g CO2/ gallon gas burned, sensu EPA
Nov. 2016 average fuel economy of 21.6 mpg, sensu EPA.
These are not the values used in the current calculation, and should be updated.

**Comment by teixeirak** [comment]
I've updated calculations for converting  Mg CO2-eq/ha to driving equivalents. Two minor changes need to be made:
- [ ] new conversion.factor=3.0.  (diving equivalents = 3*GHGV)
- [ ] new units for driving equivalents (axis label): "miles driven per parking space area (135 ft^2)".

@caseyhofford, could you please make this update?

**Comment by caseyhofford** [comment]
Done in commit: fb1ee85f8a9e4a2a024e538a4dc3fab1acf274d7, will merge this in soon

**Comment by teixeirak** [comment]
Thanks!
