### ISSUE TITLE
Add ability to select biogeochemical and/or biophysical calculations

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#13]
Krista - please define this issue. In your "Calculator Cleanup powerpoint, you had the following comment:

> It does not work to uncheck biogeochemical or biophysical. Remove those boxes.  Once it works, put them in the adjust settings part.

Apparently Carl removed these, and now we need to get them to work and add them back again.

Presumably, this would be an argument passed to the R script doing the calculation, and would affect what ends up in the figures and tables.

**Comment by teixeirak** [comment]
now covered in issue #12.
