### ISSUE TITLE
New Hosting for app_data.zip

### ISSUE THREAD

**Issue by caseyhofford** [ebimodeling/ghgvc#137]
The [download-netcdf.sh](https://github.com/ebimodeling/ghgvcR/blob/master/download-netcdf.sh) file in ghgvcR points to an old link https://www.dropbox.com/s/2g2x58fkolgnn76/app_data.zip?dl=1 that no longer has the data. We need to remake this zip file and host it somewhere new. It would probably be cheap/free to host on Google Cloud or DigitalOcean but there are many options available. It is too large to host on GitHub for free. The file is 722 mb
The simplest option, for now, might be for me to simply add it to my own Google Cloud storage and update the link. I can add it for free (I have 100gb of free storage.)

**Comment by teixeirak** [comment]
That works for now. 

I believe there's also a copy on the UIUC server, but not open access. I believe @dlebauer can answer this.

**Comment by dlebauer** [comment]
Not sure if it is possible to download using a script, but I think that this is the folder you are looking for on Box: https://uofi.box.com/v/ghgvc-inputs

**Comment by caseyhofford** [comment]
Thanks @dlebauer those are great to have, the structure of the folder there is a little different, but it has versions of most of the files we need. Thank you for all your help!

@teixeirak I think you mentioned that there are new soil maps you might want to swap in. I will wait to update this until we have those so I can package it up and put it all in one place. Thanks!!

**Comment by teixeirak** [comment]
Okay, I will work on the soils map ([this issue](https://github.com/teixeirak/ghgvc_KAT/issues/1)).

**Comment by teixeirak** [comment]
@caseyhofford, the map is now ready (see [this issue](https://github.com/teixeirak/ghgvc_KAT/issues/1)). I think this link should work: https://uofi.box.com/s/ckjponhqa7vlw084h8diyr7ve0nr4xso.
