### ISSUE TITLE
Adding additional locations

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#16]
The first step is to add instructions to the web-page, like 

> 1. Choose a location by clicking on the map
> 2. Check ecosystems that you want to evaluate
> 3. (Optional) to change default values, click 'edit' button 
> 4. Repeat 1-3 for as many locations as you want.

Later, we can discuss implementing a wizard with Krista and Evan..

**Comment by teixeirak** [comment]
This is not a high priority. Closing this issue.
