### ISSUE TITLE
Sourcing of raw CSEP input data needs consolidated + completed 

### ISSUE THREAD

**Issue by carlcrott** [ebimodeling/ghgvc#17]
per commit: 86b98a6e26ab5d0692c1664ea722e0a97d84da72
 
The *.json files containing the raw CSEPs ( "category" ,"T_A" ,"T_E", "OM_ag" ) were moved to a publicly available dir in ghgvc/public/data/* to simplify routing.

1) All references to these files should be changed to the ghgvc/public/data/* dir ( this should be all but complete )

2) Different biomes will have different CSEPs and this causes issues with populating missing fields giving incorrect outputs in the final output graphs ( EX: not all biomes have a "G_C02" field )

3) Since the above fields need populated, and the drop-downs in the #ecosystem_popup are generated from the .json data, certain fields will come up with " none " ( EX: localhost:3000 > Illinois > temperate grassland > ( edit icon ) > biophysical heading ) completing the data should fix the bug

**Comment by dlebauer** [comment]
replaced by #27
