### ISSUE TITLE
write site lat, lon to *config.xml file

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#18]
Please write `<lat>` and `<lon>` tags as children of the `<site_*_data>` tags in the config.xml files.

This will enable completion of https://github.com/ebimodeling/ghgvcR/issues/4

**Comment by potterzot** [comment]
This is already in `multisite_config.xml`, which is written when the user selects a biome. Each site is given `lat` and `lng` data, in addition to the `pft` config data. For example:

```{xml}
<site_2_data lat='24.53' lng='9.49'>
  <pft>
    <name>desert</name>
    ...
  </pft>
</site_2_data>
```
