### ISSUE TITLE
each run should have a single value for "T_E"

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#19]
T_E appears to be the duration over which the values are calculated, and has a default of 50 years.

Currently, some biomes have this tag (under `<ghgvc><site_1_data><pft>`), but this should only be given once under the `<ghgvc><options>` tag, not separately for each pft.

**Comment by teixeirak** [comment]
related to issue #12

**Comment by teixeirak** [comment]
I think this is obsolete. Closing.
