### ISSUE TITLE
Incorporate spatially explicit biophysical values for agroecosystems

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#27]
We're not getting biophysical values for any of the crops. I'm not sure why not, but this should be done for the next demo.

Current: The calculator currently has average (non-spatial) biophysical values for at least some of these crops, which were implemented as a quick fix before a calculator demo. 

TODO:
- [ ] enable calculator to use biophysical values (Rnet and LE) for 4 crop types in North America (corn, soy, miscanthus, switchgrass) and 2 in Brazil (soy and sugarcane) provided by Peter Snyder.

**Comment by teixeirak** [comment]
To summarize this issue, 
1. We have maps from Peter Snyder giving biophysical values (Rnet and LE) for 4 crop types in North America (corn, soy, miscanthus, switchgrass) and 2 in Brazil (soy and sugarcane). These are associated with bare ground baseline maps which may not be identical to the global one currently implemented in the calculator (because they're from AgroIBIS, not IBIS). None of these are currently implemented in the calculator.
2. The calculator currently has average (non-spatial) biophysical values for at least some of these crops, which were implemented as a quick fix before a calculator demo. 

Before publication, we will want to load these maps.

**Comment by potterzot** [comment]
Is this one still a high priority?

**Comment by teixeirak** [comment]
It's still important, although I would rank it below #12, #21,  #86, #87.

**Comment by teixeirak** [comment]
This issue was also covered in #4 , now closed.

**Comment by teixeirak** [comment]
From my (perhaps faulty) understanding of biome.R, the biophysical data for all of the crops for which biophysics have been modeled (corn, soy, sugarcane, miscanthus, switchgrass) are being loaded, and the only obstacle to their being incorporated into the calculations is two lines of code (https://github.com/ebimodeling/ghgvcR/blob/master/R/biome.R#L446-L447) that set values for agroecosystems to zero. If this is the case, fixing this issue would be a very quick fix. @potterzot, is my interpretation correct?

**Comment by teixeirak** [comment]
Closing this for now, as these ecosystems have disappeared from the current version. See issue #125.
