### ISSUE TITLE
re-implement map in R shiny server

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#36]
This is a proposal that would replace gh-25 and give scientists more control over the mapping application, and reduce dependency on the google maps api that seems rather difficult to implement. 

Here is an example of such an interface: http://glimmer.rstudio.com/jcheng/leaflet-demo/

This feature would be used by ghgvc as well as [PEcAn](https://github.com/PecanProject/pecan), and [BETYdb](https://github.com/PecanProject/bety) web interfaces.

**Comment by teixeirak** [comment]
Fine with me.
