### ISSUE TITLE
Biome Map (which was removed) re-appears at random 

### ISSUE THREAD

**Issue by jhprobert** [ebimodeling/ghgvc#41]
The Biome Map appears somewhat at random when placing different pushpins on the globe. I have noticed this occurs after selecting the South Pole, bodies of water, and increasing/decreasing the magnification on the map. The Biome Map appears all over the globe. 
1. Africa
![africa](https://f.cloud.github.com/assets/6640359/2127561/69bf1534-9270-11e3-9738-142e845d2dd9.png)
2. Planet
![world](https://f.cloud.github.com/assets/6640359/2127572/806b03a6-9270-11e3-9cb2-c29843883981.png)

**Comment by teixeirak** [comment]
Old bug, which has likely been taken care of; closing.
