### ISSUE TITLE
Biomes are sometimes available for selection in water bodies.

### ISSUE THREAD

**Issue by jhprobert** [ebimodeling/ghgvc#42]
UPDATE

The part about clicking in the middle of the ocean has been resolved [(comment below)](https://github.com/ebimodeling/ghgvc/issues/42#issuecomment-235161502) except for locations very near shore. The remaining work is to add a high resolution mask to filter any points on the water rather than using the lower resolution grid on which the data are provided.

---

There have been some instances of data being selected for bodies of water.

1. At (60.61, 32.10) there is a listing for Boreal Forest. The mark is in the middle of a lake. 
![boreal forest- lake](https://f.cloud.github.com/assets/6640359/2127621/29a9c4d4-9271-11e3-8564-a3920c450a30.png)
2. At (41.93, -81.19), there is US Corn in Lake Erie.
![corn in lake erie](https://f.cloud.github.com/assets/6640359/2127655/7dca72e8-9271-11e3-85f9-8680b9a486fe.png)
3. At (50.43, -98.24), Lake Manitoba is being recognized as temperate forest.
![image](https://f.cloud.github.com/assets/6640359/2127669/a4ec9cfc-9271-11e3-9b45-5879ac21ab18.png)

**Comment by potterzot** [comment]
I've fixed this to some extent, but this may also be a problem of resolution. If a location close enough to shore is selected, the closest grid point is on land, and it has a biome.

**Comment by teixeirak** [comment]
This original issue was largely solved, but has reappeared and is currently covered by issue #83. Closing this version.
