### ISSUE TITLE
Internet explorer outputting the same biomes regardless of biome selection

### ISSUE THREAD

**Issue by jhprobert** [ebimodeling/ghgvc#44]
I am using Internet Explorer for the calculator. I initially made two selections when running the simulation, tropical savannah and sugarcane. These results are not changing. In image 1, I have placed a pushpin in a desert. It allows me to select, but the values remain the same. 
![image](https://f.cloud.github.com/assets/6640359/2247373/00992834-9d6e-11e3-9976-98876a50e3a6.png)

In image 2, I have  placed a pushpin in New Zealand, and have received the same results.
 
![image](https://f.cloud.github.com/assets/6640359/2247422/95aa92be-9d6e-11e3-84cb-1547b9aec7cd.png)

Also, this textbox is assuming New Zealand is spelled incorrectly.

**Comment by teixeirak** [comment]
I think this is obsolete.
