### ISSUE TITLE
Organize netcdf files

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#5]
The netcdf files are disorganized and split up, which fails to take advantage of the format. We need to document the data and combine data sets into a single file that is easy (quick and logical) to read.

The data are here: https://github.com/ebimodeling/ghgvc/tree/master/netcdf

Presumably the metadata are in [app/controllers/workflows_controller.rb](https://github.com/ebimodeling/ghgvc/blob/master/app/controllers/workflows_controller.rb). 

TODO:

1. concatenating and appending data.
    perhaps separate by source, but it makes more sense to combine all variables into a single folder, and the separation of crops into US and Brazil is redundant with the map and lat/lon coordinates.
2. stored data separately from source code (and perhaps remove from history to reduce checkout size)
3. re-grid similar datasets, combine into single file
4. add species / pft as a dimension, see CF discussion http://kitt.llnl.gov/trac/ticket/99 e.g 
 * 'taxon_identifier' as standard_name; --> scientific name

**Comment by dlebauer** [comment]
List of combined files are here: https://gist.github.com/dlebauer/7cc778317e45bb36a74b

@hmb1 did the following

* combined files with multiple variables into a subset of files
  * here is a list of files and variables https://gist.github.com/dlebauer/7cc778317e45bb36a74b
  * previously, each lookup of a value required the same find nearest neighbor [app/controllers/workflows_controller.rb](https://github.com/ebimodeling/ghgvc/blob/master/app/controllers/workflows_controller.rb)
* [ ] need to create a test harness in Ruby

**Comment by hmb1** [comment]
Hi David,
   uploaded yesterday to my user on pecandev *saatchi_final.nc* which is 
a combination of america/africa/asia
   I checked it with ncdump & ncks
   ....Henry

**Comment by dlebauer** [comment]
I've made these data available on box at https://uofi.box.com/saatchi-ncdf

I've also removed refactoring code from the scope of this issue - that is covered in #70

**Comment by potterzot** [comment]
I think this should be closed, since it's essentially a replication of #59 and #64.
