### ISSUE TITLE
rails permissions

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#51]
the rails app does not appear to be writing out an output.json file

perhaps insufficient permissions?

as a result, I get this error when running the calculator:
```bash
Completed 500 Internal Server Error in 38ms

Errno::ENOENT (No such file or directory - /usr/local/ghgvc/tmp/out/output.json):
  app/controllers/workflows_controller.rb:131:in `read'
  app/controllers/workflows_controller.rb:131:in `create_config_input'
```

**Comment by dlebauer** [comment]
@potterzot

**Comment by potterzot** [comment]
There is not a permissions issue, but this:

>I think that the best solution would be to move the ghgvcr_script.R to the rails repository (where would it go? local?) and then the ghgvcr_instantiation_path=#{Rails.root}/local/ghgvcr_script.R

Is maybe something you'd like me to do before closing this issue?

Right now the script is source (line 127 of workflows_controller.rb) as:

`rcmd = "cd #{ghgvcR_instantiation_path} && ./inst/scripts/calc_ghgvc.R"`

**Comment by potterzot** [comment]
All R scripts are now in ghghv/script/.
