### ISSUE TITLE
Chart errors

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvc#75]
@dlebauer In the development version of ghgvc, there are 5 charts for which no values are plotted. These charts are different from the 3 that are currently displayed at http://ecosystemservicescalc.org.

The charts are created in [calculator.js](https://github.com/ebimodeling/ghgvc/blob/development/app/assets/javascripts/calculator.js), and it looks like the data used to be passed to a "run.php" script, which then returned values to plot, but I can't find a "run.php" script at this point.

**Comment by dlebauer** [comment]
The js charts are deprecated in favor of the plots generated by R. I suspect that the old plumbing remains, but that calculator.js is obsolete.

**Comment by potterzot** [comment]
Hoping to get this done tomorrow, it shouldn't take long to port over. I think the original R code for the plots is in [ghgvc_script.R](https://github.com/ebimodeling/ghgvcR/blob/master/src/ghgvc_script.R) starting at line 100.

**Comment by potterzot** [comment]
@dlebauer Should be fixed. A working [demo is available](http://ec2-52-38-133-219.us-west-2.compute.amazonaws.com/).
