### ISSUE TITLE
Fix scrambled ecosystem types

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#76]
Ecosystem types are scrambled, both in terms of options displayed for a given location and what’s displayed in the output.  

Regarding options displayed, I can click on a given location (e.g., the Amazon) and get what seems to be a random assortment of ecosystem options (boreal forest, temperate forest, desert, etc). I can't make out any pattern to this error, although it seems there may sometimes be a link to the previously selected ecosystem type. When there's more than one type of ecosystem listed (e.g., natural and agroecosystems), it does seem that the combinations are always reasonable (e.g., temperate forest with temperate cropland as opposed to tropical cropland).

Regarding output display, the ecosystem types selected do not necessarily match those selected, and site numbers can be switched. I've had at least one instance where ecosystems selected in the previous run were the ones displayed.  It looks like the site numbers issue is a simple reversal of order; for 3 sites, site 3 becomes site 1, site 2 stays site 2, site 1 becomes site 3.

**Comment by potterzot** [comment]
Due to two separate issues detailed in the latest development commit of ghgvcR. Should be fixed now, as reflected by [demo server](http://52.38.133.219/).

**Comment by teixeirak** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6355854/15120641/a2526b54-15e4-11e6-9d3e-1b90a06d3176.png)

**Comment by teixeirak** [comment]
Addendum to the above comment: When I ran the above setup, the output was completely mismatched. See the attached screenshot. Note that I did not select anything for location 3 before running the calculator, so I would expect to see results for two ecosystem types: tropical forest site 1 and tropical forest site 2. Instead I get this: 
![untitled2](https://cloud.githubusercontent.com/assets/6355854/15120916/04c9b386-15e6-11e6-85c4-64885f6f4b24.png)

**Comment by potterzot** [comment]
@teixeirak hmm, thanks. Will take a look at this tonight.

**Comment by teixeirak** [comment]
Any update on this?

**Comment by potterzot** [comment]
I haven't quite resolved it yet, but hope to have it done here in the next couple of days. I'm also hoping to get the other issues taken care of early this week as well.

**Comment by teixeirak** [comment]
Can we please get this resolved ASAP?

**Comment by potterzot** [comment]
Fixed - Good example of need to remove all files in `/tmp/run` and `tmp/out` each time the site is loaded. Otherwise a bug in ghgvcR can leave those files unchanged, and ghgvc doesn't know that they are from the previous run. Created a new issue #78 regarding this.
