### ISSUE TITLE
cleanup of biome selection display

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#81]
Please alter the ecosystem selection display as follows:
1- Natural vegetation types--including forest, savanna, shrubs, and grasses--should be listed under native vegetation. Agricultural ecosystems--including pasture, cropland, and specific crop types (maize, soy, sugarcane, switchgrass, miscanthus)--should be listed under Agroecosystem.  Currently, pasture sometimes shows up under Native and sometimes under Agroecosystem.
2- Change some ecosystem names: "BR soy" to "Soybean", "BR sugarcane" to "Sugarcane",  "US corn" to "Maize", and "pasture" to "Grassland pasture"
3- Capitalize all ecosystem type names (currently some specific crop types aren't capitalized). 
4- put an asterisk after the vegetation type(s) identified by SYNMAP. Then add a footnote at the bottom of the box saying "*Most likely vegetation type(s) in the year 2000."

**Comment by potterzot** [comment]
Repost with list:

* [ ] Natural vegetation types--including forest, savanna, shrubs, and grasses--should be listed under native vegetation. Agricultural ecosystems--including pasture, cropland, and specific crop types (maize, soy, sugarcane, switchgrass, miscanthus)--should be listed under Agroecosystem. Currently, pasture sometimes shows up under Native and sometimes under Agroecosystem.

* [ ] Change some ecosystem names: "BR soy" to "Soybean", "BR sugarcane" to "Sugarcane", "US corn" to "Maize", and "pasture" to "Grassland pasture"

* [ ] Capitalize all ecosystem type names (currently some specific crop types aren't capitalized). 

* [ ] put an asterisk after the vegetation type(s) identified by SYNMAP. Then add a footnote at the bottom of the box saying "*Most likely vegetation type(s) in the year 2000."

**Comment by potterzot** [comment]
I've added a "is_synmap" variable to each biome_default. This should allow someone to modify the rails code to add the asterisk if the value is TRUE. Haven't gotten farther than that, and might not get there this week.

**Comment by teixeirak** [comment]
The last item in this issue (put an asterisk after the vegetation type(s) identified by SYNMAP) is now complete. Many thanks, @caseyhofford!
