### ISSUE TITLE
improvements to Google map display

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#84]
Now that we have better spatial resolution, is it possible to allow closer zoom on the google map? Also, is it possible to give the option to turn on political boundaries, etc? These would be nice improvements if they can be done easily, but are not essential.

**Comment by potterzot** [comment]
Increased the zoom from 5 to 7. I believe it goes up to 9, but not sure. To further change, change line 223 of [workflows.js](https://github.com/ebimodeling/ghgvc/blob/development/app/assets/javascripts/workflows.js), variable `mapMaxZoom`.

As far as the political boundaries, I am not sure how to do them. I'm sure it's doable, but for me at least it would be a significant time investment. I couldn't find an easy toggle to add a political boundary layer.
