### ISSUE TITLE
scale map box

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#90]
Can we scale the map box such that full zoom out shows one complete world map with no repetition? Currently, if I want to show a world map (which I want to do for our publication), I have to either show only part of the map or have parts repeated.
<img width="1440" alt="screen shot 2016-08-31 at 8 45 42 am" src="https://cloud.githubusercontent.com/assets/6355854/18129207/ad2fcf9a-6f57-11e6-8127-45fdbaa9cf85.png">
<img width="1440" alt="screen shot 2016-08-31 at 8 45 49 am" src="https://cloud.githubusercontent.com/assets/6355854/18129208/ad35e4a2-6f57-11e6-8a78-99ac4a75ede8.png">

**Comment by potterzot** [comment]
Oddly, it doesn't seem possible. Which seems weird, so I'm probably wrong, but with zoom 1, we get repeats of some areas, and with zoom 2, we get not quite the whole earth. From what I can tell, this is related to the size of the map "box" in the site, so the thing to do would either be to make the map canvas bigger or smaller. Changing it to 1025 pixels gets the entire earth map to fit nicely, but then I have to change the rest of the site to get things to line up. Is anyone involved in the project a better CSS person than I am? I can make my way but it's cludgy.

**Comment by dlebauer** [comment]
@gsrohde knows css

**Comment by potterzot** [comment]
Great! [This is the file](https://github.com/ebimodeling/ghgvc/blob/development/app/assets/stylesheets/workflows.css.scss) that controls the map width. As of right now it is all aligned, as you can [see in the demo](http://52.38.211.88/), but there may be better ways to do it.

**Comment by teixeirak** [comment]
This is much better. Could you please adjust the vertical size as well so that New Zealand and the tip of S. America show up? (No need to see Antarctica.)

**Comment by potterzot** [comment]
Done - see [line 31](https://github.com/ebimodeling/ghgvc/blob/development/app/assets/stylesheets/workflows.css.scss). Additional adjustments can be easily made by changing that value.
