### ISSUE TITLE
fix bug: can't drop pin in S China

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#91]
I can't drop a pin anywhere in a large region of S China. The attached image has pins dropped around the approximate edges of this region. 
Another bug that is probably related-- no ecosystems show up at pin 5 in the attached image.
 
<img width="1440" alt="screen shot 2016-08-31 at 9 46 40 am" src="https://cloud.githubusercontent.com/assets/6355854/18131187/e05a992e-6f5f-11e6-841f-34b87d2a92e3.png">

**Comment by potterzot** [comment]
Fixed
