### ISSUE TITLE
fix bug: model freezes on pasture

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#92]
I don't know what triggers it, but the model freezes sometimes. Here's a screenshot of an example where this happened ( you can see lat-long and ecosystem types selected). 

<img width="1440" alt="screen shot 2016-08-31 at 1 03 57 pm" src="https://cloud.githubusercontent.com/assets/6355854/18138580/764f6232-6f7b-11e6-951b-20ee76ea206f.png">

**Comment by teixeirak** [comment]
I've isolated the problem. It freezes on grassland pasture.

**Comment by potterzot** [comment]
Fixed
