### ISSUE TITLE
fix graphing

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#94]
The latest update seems to have reverted to an old graphing script that doesn't work. Please fix ASAP.

<img width="1440" alt="screen shot 2016-09-06 at 10 27 56 am" src="https://cloud.githubusercontent.com/assets/6355854/18277483/aa7a7740-741c-11e6-8aec-a6d71b18a22f.png">

**Comment by potterzot** [comment]
I can't reproduce this. Can you provide a lat/lon and biome combo that make
the old graphing come up?

Also - we could remove the call to old plot code entirely.

--
Nicholas Potter
http://potterzot.com
9C73 3AAA 6D99 86F1 F8F4 601D 298F 8713 1BE6 5941

**Comment by dlebauer** [comment]
@potterzot yes ... not sure why this popped up but I see no reason to keep the old plotting code ...

**Comment by teixeirak** [comment]
I can't reproduce it now either. But I agree; let's get rid of that old code.

**Comment by teixeirak** [comment]
This is reproduced in issue #96. I'm not sure how to merge the issues, so I'll just close this one.
