### ISSUE TITLE
disallow temperate savannas

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#95]
When SYNMAP predicts grass and trees outside of the tropics, savanna (grass + trees) is listed as an option, but we have not defined a savanna ecosystem type outside the tropics. Please make a rule that savanna only appears as an option in the climate zones with which ecosystem type 'S1' is associated. Alternatively, if this is complicated, make the rule that it only appears between latitudes -23.5 and 23.5.

**Comment by potterzot** [comment]
Fixed this in ghgvcR. Reference [this code block](https://github.com/ebimodeling/ghgvcR/blob/5d36664d6e94c26d357827bc1422e6ebb24b0e0e/R/biome.R#L444-L451) to add additional exclusions or to remove them.
