### ISSUE TITLE
fix bug: calculator reverts to old graphing scheme when ecosystem with no data is selected

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#96]
If I select an ecosystem for which there are no data (as the only ecosystem selected)-- for example, savanna outside the tropics-- the calculator reverts to the old graphing scheme (see image). Please fix.

<img width="1440" alt="screen shot 2016-09-27 at 10 06 50 am" src="https://cloud.githubusercontent.com/assets/6355854/18877142/3ccd38e8-849a-11e6-94b3-e31c9190b742.png">

**Comment by potterzot** [comment]
I disabled the old graphing call, so this should no longer happen. I can't get it to happen on my machine, but if somehow it is happening we can reopen this.

**Comment by teixeirak** [comment]
I'm still getting it. I get it when I click around the US midwest (as in image above) until I get savanna as an option, and then select that (and only that).

**Comment by potterzot** [comment]
Okay, thanks. I'll take a look at it.

**Comment by potterzot** [comment]
For future reference, (41.32, -93.50) selecting savannah will replicate this error. Likely applies to any ecosystem for which we have no data. Probably tied to Issue #95 disallow temperate savannahs. But also should generally disable/remove this code.

But - that means this issue should be fixed before #95 is fixed, or it may lurk... Working on it now.

**Comment by potterzot** [comment]
Fixed. highcharts.js is disabled, ref [this block](https://github.com/ebimodeling/ghgvc/blob/b0c3e1fa62b83bc691d827cfc49cd11fcf30068b/app/assets/javascripts/workflows.js#L628-L642). 

I've also updated some of the container names to be no longer highchart specific.

The code to create the highcharts themselves is still present in [calculator.js](https://github.com/ebimodeling/ghgvc/blob/b0c3e1fa62b83bc691d827cfc49cd11fcf30068b/app/assets/javascripts/calculator.js)
