### ISSUE TITLE
Create and track unique outputs for each run

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#99]
currently, the calculator creates the ghgv.csv, ghgv.json, biome.json, and multisite_config.xml for each run.

If 2 users are using the site at once they could download the wrong file. This could be solved by having files that are unique to a particular session.

Right now, I will mark this as low priority because the user base is sufficiently small that the probability that this will occur is very low (P<<0.001) (except during demos when many people are trying it out ... ).

**Comment by teixeirak** [comment]
This may be fixed; need to check.

**Comment by teixeirak** [comment]
These files no longer exist-- R communicates directly with Ruby. Thus, this issue should be resolved.
